name: Build and Release Worker Module and Docker Image

on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - v0.*


permissions:
  packages: write
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout worker repository
        uses: actions/checkout@v3
        with:
          repository: h3xitsec/h3xrecon-worker
          path: h3xrecon-worker
          ref: ${{ github.ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'
          
      - name: Install build dependencies
        working-directory: h3xrecon-worker
        run: |
          pwd
          ls -laR
          python -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt
      
      - name: Get versions from __about__.py
        id: get_version
        working-directory: h3xrecon-worker
        run: |
          VERSION=$(python -c "import sys; sys.path.append('src'); from h3xrecon_worker.__about__ import __version__, __core_version__, __plugin_version__;
          print(f'Worker: v{__version__}, Core: v{__core_version__}, Plugins: v{__plugin_version__}')")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "core_version=$__core_version__" >> $GITHUB_OUTPUT
          echo "plugin_version=$__plugin_version__" >> $GITHUB_OUTPUT
      
      - name: Checkout core repository
        uses: actions/checkout@v3
        with:
          repository: h3xitsec/h3xrecon-core
          path: h3xrecon-core
          ref: ${{ github.ref }}
      
      - name: Checkout plugins repository
        uses: actions/checkout@v3
        with:
          repository: h3xitsec/h3xrecon-plugins
          path: h3xrecon-plugins
          ref: ${{ github.ref }}

      - name: Build package
        working-directory: h3xrecon-worker
        run: |
          python -m build
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          files: |
            h3xrecon-worker/dist/*.whl
          repository: h3xitsec/h3xrecon
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_PAT }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push h3xrecon-worker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./h3xrecon-worker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/h3xrecon_worker:${{ steps.get_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
