name: Build and Release Worker Module

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - release/*

permissions:
  packages: write
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout worker repository
        uses: actions/checkout@v3
        with:
          repository: h3xitsec/h3xrecon-worker
          path: h3xrecon-worker
          ref: ${{ github.ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'
          
      - name: Install build dependencies
        working-directory: h3xrecon-worker
        run: |
          python -m pip install --upgrade pip
          pip install hatchling
          pip install -r requirements.txt
      
      - name: Get versions from __about__.py
        id: get_version
        working-directory: h3xrecon-worker
        run: |
          python -c "
          with open('src/h3xrecon_worker/__about__.py', 'r') as f: 
              exec(compile(f.read(), 'src/h3xrecon_worker/__about__.py', 'exec'), globals())
          print(f'all_versions1=Worker: v{__version__}, Core: v{__core_version__}, Plugins: v{__plugin_version__}')
          print(f'version={__version__}')
          print(f'core_version={__core_version__}')
          print(f'plugin_version={__plugin_version__}')
          " >> $GITHUB_OUTPUT
      
      - name: Checkout core repository
        uses: actions/checkout@v3
        with:
          repository: h3xitsec/h3xrecon-core
          path: h3xrecon-core
          ref: v${{ steps.get_version.outputs.core_version }}
      
      - name: Checkout plugins repository
        uses: actions/checkout@v3
        with:
          repository: h3xitsec/h3xrecon-plugins
          path: h3xrecon-plugins
          ref: v${{ steps.get_version.outputs.plugin_version }}

      - name: Build package
        working-directory: h3xrecon-worker
        run: |
          python -m hatchling build
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: |
            h3xrecon-worker/dist/*.whl
          repository: h3xitsec/h3xrecon-worker
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_PAT }}